version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_web
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --ws-ping-interval 20 --ws-ping-timeout 20
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"  
    
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1